version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - gocritic
    - goimports
    - gosec
    - misspell
    - revive
    - unconvert
    - unparam
    - whitespace

run:
  timeout: 5m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0