# Test coverage configuration for Eph
# Path to coverage profile file (output of `go test -coverprofile` command).
profile: coverage.out

# Holds coverage thresholds percentages, values should be in range [0-100].
threshold:
  # Minimum coverage percentage required for individual files.
  file: 70

  # Minimum coverage percentage required for each package.
  package: 80

  # Minimum overall project coverage percentage required.
  total: 75

# Override rules for specific packages (most specific to most general)
override:
  # CLI commands don't need high coverage (mostly cobra boilerplate)
  - path: ^cmd/
    threshold:
      file: 50
      package: 60

  # Version package is simple constants
  - path: ^pkg/version
    threshold:
      file: 60
      package: 70

  # Internal server handlers might have lower coverage due to integration nature
  - path: ^internal/server/handlers
    threshold:
      file: 65
      package: 75

  # Database models/migrations might be harder to test in unit tests
  - path: ^internal/db
    threshold:
      file: 60
      package: 70

# Exclude files from coverage statistics
exclude:
  paths:
    # Generated files
    - \.pb\.go$           # Protocol buffer generated files
    - \_gen\.go$          # Generated files
    - \_generated\.go$    # Generated files

    # Test files (coverage tools sometimes include these)
    - \_test\.go$

    # Mock files
    - mock_.*\.go$
    - .*_mock\.go$

    # Example/demo code
    - ^examples/

    # Documentation
    - ^docs/

    # Vendor directory (if used)
    - ^vendor/

    # Testdata directories
    - testdata/

    # Main functions (often hard to test)
    - ^cmd/.*/main\.go$

# Report generation settings
report:
  # Print coverage report to stdout
  print: true

  # Print uncovered files
  print-uncovered: true

  # Print coverage for each package
  print-packages: true
